name: CI

on:
  push:
    branches:
     - main
    paths:
    - '.github/**'
    - 'src/**'
    - 'include/**'
    - 'test/**'
    - 'CMakeLists.txt'
  pull_request:
    branches:
     - main
    paths:
    - '.github/**'
    - 'src/**'
    - 'include/**'
    - 'test/**'
    - 'CMakeLists.txt'
     
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update
      - uses: actions/checkout@v2
        with:
          repository: bitcoin-core/secp256k1
          path: libsecp256k1
      - name: Build and install libsecp256k1
        run: |
          brew install libtool automake
          cd libsecp256k1
          ./autogen.sh
          ./configure --enable-module-recovery
          make
          sudo make install
          pkg-config --cflags --libs libsecp256k1
      - name: Build and install libtap
        run: |
          cd libtap
          make
          sudo make install
          pkg-config --cflags --libs tap
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DENABLE_TESTING=ON ..
          make
          ls -lh
      - name: Test
        run: |
          cd build
          make test ARGS="-V"
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Envinfo
        run: npx envinfo
      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update
      - uses: actions/checkout@v2
        with:
          repository: bitcoin-core/secp256k1
          path: libsecp256k1
      - name: Build and install libsecp256k1
        run: |
          cd libsecp256k1
          ./autogen.sh
          ./configure --enable-module-recovery
          make
          sudo make install
          pkg-config --cflags --libs libsecp256k1
      - name: Build and install libtap
        run: |
          cd libtap
          make
          sudo make install
          pkg-config --cflags --libs tap
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DENABLE_TESTING=ON ..
          make
          ls -lh
      - name: Test
        run: |
          cd build
          make test ARGS="-V"
